// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JvxDB8Q5d38c3kPlwjSxYu5vfTVmNTc',
    appId: '1:285686091078:web:590addb18ae974e796a947',
    messagingSenderId: '285686091078',
    projectId: 'aspire-mindtrace',
    authDomain: 'aspire-mindtrace.firebaseapp.com',
    storageBucket: 'aspire-mindtrace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbGEc8LFTZ_DuXgetRO0p8MhGvay5xS8',
    appId: '1:285686091078:android:deb1100d1c1dad0696a947',
    messagingSenderId: '285686091078',
    projectId: 'aspire-mindtrace',
    storageBucket: 'aspire-mindtrace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLx_FiFry0jXyn6tV0UlroNSqx8vA7QU',
    appId: '1:285686091078:ios:270e00935c13a06c96a947',
    messagingSenderId: '285686091078',
    projectId: 'aspire-mindtrace',
    storageBucket: 'aspire-mindtrace.firebasestorage.app',
    iosBundleId: 'com.example.mindtrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANLx_FiFry0jXyn6tV0UlroNSqx8vA7QU',
    appId: '1:285686091078:ios:270e00935c13a06c96a947',
    messagingSenderId: '285686091078',
    projectId: 'aspire-mindtrace',
    storageBucket: 'aspire-mindtrace.firebasestorage.app',
    iosBundleId: 'com.example.mindtrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JvxDB8Q5d38c3kPlwjSxYu5vfTVmNTc',
    appId: '1:285686091078:web:46150bec11f3295e96a947',
    messagingSenderId: '285686091078',
    projectId: 'aspire-mindtrace',
    authDomain: 'aspire-mindtrace.firebaseapp.com',
    storageBucket: 'aspire-mindtrace.firebasestorage.app',
  );
}
